readingDataPointsFilters:

  - SurfaceNormalDataPointsFilter:
      # knn: 1
      epsilon: 3.16
      keepNormals: 1
      keepDensities: 1
  - ObservationDirectionDataPointsFilter
  - OrientNormalsDataPointsFilter 

referenceDataPointsFilters:
  - SurfaceNormalDataPointsFilter:
      # knn: 5
      epsilon: 3.16
      keepNormals: 1
      keepDensities: 1
      
matcher:
  KDTreeMatcher:
    maxDist: 0.5
    # knn: 1
    epsilon: 3.16

# outlierFilters:
#   - MaxDistOutlierFilter:
#       maxDist: 1
  # - TrimmedDistOutlierFilter:
  #    ratio: 0.85
  # - SurfaceNormalOutlierFilter:
  #    maxAngle: 0.42

errorMinimizer:
  PointToPlaneErrorMinimizer

transformationCheckers:
  - CounterTransformationChecker:
      maxIterationCount: 5
  - DifferentialTransformationChecker:
      minDiffRotErr: 0.001
      minDiffTransErr: 0.01
      smoothLength: 3 

inspector:
 NullInspector
 
logger:
  NullLogger

  
