matcher:
  KDTreeMatcher:
    knn: 1

outlierFilters:
  - MaxDistOutlierFilter:
      maxDist: 1

errorMinimizer:
  PointToPointErrorMinimizer

transformationCheckers:
  - CounterTransformationChecker:
      maxIterationCount: 10
  - DifferentialTransformationChecker:
      minDiffRotErr: 0.001
      minDiffTransErr: 0.01
      smoothLength: 4 

inspector:
 NullInspector
 
logger:
  FileLogger

  
